# Generated by Django 5.1.4 on 2025-01-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_remove_job_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_tybe',
            field=models.CharField(choices=[('full_time', 'full_time'), ('part_time', 'part_time')], default='', max_length=10),
            preserve_default=False,
        ),
    ]
