# Generated by Django 5.1.4 on 2025-01-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='img',
            field=models.ImageField(default=2, upload_to='job/'),
            preserve_default=False,
        ),
    ]
