# Generated by Django 5.1.4 on 2025-03-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_apply_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='created_At',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
